# Generated by Django 4.2.3 on 2023-07-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_car_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_url',
            field=models.URLField(verbose_name='Image URL'),
        ),
    ]
