# Generated by Django 4.2.2 on 2023-06-28 10:58

import django.core.validators
from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='name',
            field=models.CharField(default=1, max_length=20, validators=[django.core.validators.MinLengthValidator(2), web.models.only_letters_name_validator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
