# Generated by Django 4.2.1 on 2023-06-12 12:48

from django.db import migrations, models
import photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='pet_photos/', validators=[photos.validators.validate_file_size_greater_than_5mb]),
        ),
    ]
