# Generated by Django 4.2.1 on 2023-06-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_alter_photo_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='date_of_publication',
            new_name='publication_date',
        ),
    ]
