# Generated by Django 4.2.2 on 2023-06-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_person_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='persons/'),
        ),
    ]
