# Generated by Django 4.2.1 on 2023-06-13 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_photocomment_photolike_remove_like_to_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photocomment',
            old_name='comment_text',
            new_name='text',
        ),
    ]
