# Generated by Django 4.2.1 on 2023-05-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_nullblankdemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.CharField(choices=[('jr', 'Junior'), ('reg', 'Regular'), ('sr', 'Senior')], default=1, max_length=25),
            preserve_default=False,
        ),
    ]
