# Generated by Django 4.2.1 on 2023-05-15 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_project_employee_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='project',
            field=models.ManyToManyField(related_name='employees', to='web.project'),
        ),
        migrations.CreateModel(
            name='EmployeesProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.employee')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.project')),
            ],
        ),
    ]
